# Generated by Django 3.1.6 on 2021-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210324_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=5000)),
                ('email', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=5000)),
                ('zip_code', models.CharField(max_length=5000)),
                ('phone_no', models.CharField(max_length=5000)),
            ],
        ),
    ]
